name: WakaTime Readme Stats

on:
  schedule:
    - cron: "0 0 * * 6" #every saturday cuz why not
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PAT_1 }}

          #removed and retained features from my redme.md file
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          # SHOW_PROFILE_VIEWS: "True"
          SHOW_UPDATED_DATE: "False"
          SHOW_LANGUAGE: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SYMBOL_VERSION: "1"
          BLOCKS: "->"
          SHOW_TITLE: "False"
          LANG_COUNT: "10"
